name: "lightbasenl/aws-codepipeline-slack"
author: "lightbase.nl"
description:
  "Trigger an AWS CodePipeline from GitHub Actions with Slack notifications"
inputs:
  pipeline:
    description: "The name of the CodePipeline"
    required: true
  wait_completion:
    description: "Monitor CodePipeline and update Action"
    required: false
    default: "true"
  slack_token:
    description: "Slack APP oAuth token"
    required: false
  slack_channel:
    description: "Slack channel for notification"
    required: false
outputs:
  data:
    description: "Expose Slack and CodePipeline state"
runs:
  using: "node16"
  main: "src/index.js"
